config/routes.rb
Epipen::Application.routes.draw do
  
  
  get "welcome/index"
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'users#kids'
  
  resources :users do
    member do
      get 'kid_details'
    end
    collection do
      get 'create_kid_form'
      get 'kids'
      post 'create_kid'
    end  
  end

end

app/models/kid.rb
class Kid < ActiveRecord::Base

  belongs_to :user
  
  belongs_to :school
end

app/models/school.rb
class School < ActiveRecord::Base

  has_many :kids, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :kids
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
  raise params.inspect
  #   super(resource)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  
  def create_kid
    @amount = params[:allergy] ? 600 : 0
    @kid = Kid.create name: params[:name], school_id: params[:school], user_id: current_user.id, allergy: params[:allergy], amount: @amount
    redirect_to root_path
  end
  
  def kids
    @user = current_user
    @kids = current_user.kids
    @users = User.all
  end
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Epipen</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container-narrow">
  <div class="masthead">
    <%= render 'layouts/user_header' %>
    <h3 class="muted"><%= link_to "Epipen", root_path %></h3>
    
  </div>
  <hr />
  <%= yield %>
</div>


</body>
</html>

app/views/users/create_kid_form.html.erb
<%= form_tag(create_kid_users_path) do %>
  
  Name : <%= text_field_tag 'name' %> <br/><br/>
 
  School : <%= select_tag 'School', options_from_collection_for_select(School.all, 'id', 'name')  %>  
  <br/><br/>
  
  Allergy : <br/><br/>
  
  Yes : <%= radio_button_tag 'allergy', true , true %>
  
  
  No : <%= radio_button_tag 'allergy', false, false %>
  
  <br/><br/>
  
  <%= submit_tag "Submit" %>
<% end %>

app/views/users/kids.html.erb
<div class="container">

<%= link_to "Upload kid details", create_kid_form_users_path %><br/> <br/>
<table border='1'>
  <% if @kids.present? %>
  <tr>
    <th> Name of the kid </th>
    <th>Allergy</th>
    <th>Amount</th>
  </tr>
  <% else %>
    <div class="alert alert-danger">
  <strong>Please upload your kid details!</strong>
</div>
  <% end %>
  <% @kids.each do  |kid| %>
  <tr>
    <td><%= kid.name %></td>
    <td><%= kid.allergy  ? "Yes" : "No" %></td>
    <td><%= kid.allergy ? "600" : "0" %></td>
  </tr>
  <% end %>
  
 </table> 
  <br/><br/>
  
  <h1>Contribution of each parent</h1>
  
 <table border='1'>  
  <% if @users.present? %>
  <tr>
    <th>Email of the parent </th>
    <th>Kids</th>
    <th>Amount</th>
  </tr>
  <% else %>
   <div class="alert alert-danger">
  <strong>No other parent contributions</strong>
</div> 
  <% end %>
  <% @users.each do  |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><% user.kids.map(&:name).each do |name| %>
          <%= name %><br/>
        <% end %>
    </td>
    <td><%= user.kids.map(&:amount).inject(0){|sum,x| sum + x } %></td>
  </tr>
  <% end %>
  
  
</table>

</div>

app/views/welcome/index.html.erb
<h1>Epipen</h1>

<%= link_to "create kid", create_kid_form_users_path %>